### ISSUE TITLE
How to check status apps whether working or not

### ISSUE THREAD

**Issue by bobolat** [MyHealthTeams/google-app-conversion-tracker#10]
hello there..currently im using this plugin to apply adword feature into my apps. the problem is i dont know how to check whether it is already working or not. in the doc they says it will show pinging, but i dont know where the pinging display..can u help me?

**Comment by pnock** [comment]
You should be able to see something logged in the console of xcode/dev studio. Insert a debugger and you should be able to run the GappTrack.track() direct from the command line in debug.

**Comment by bobolat** [comment]
@pnock so there is no way i want to check it is work or not withoput xcode/dev studio?
