### ISSUE TITLE
build failed for ios

### ISSUE THREAD

**Issue by tamirla** [MyHealthTeams/google-app-conversion-tracker#4]
When trying to build a cordova (ionic) project for ios after adding this plugin to my project I'm getting the following error: ld: library not found for -lGoogleConversionTracking

**Comment by matteocasadei** [comment]
Same problem on xCode 6.1.1:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GoogleConversionPing", referenced from:
      objc-class-ref in GoogleAppTracking.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is there a solution to fix this problem?
Thanks.

**Comment by matteocasadei** [comment]
In my case I had to run a product->clean via Xcode and everything seems to be ok.
Anyway, @pnock thanks a lot for the plugin. Great job!

**Comment by robbieboydcolenso** [comment]
Hi, I am getting the same error and I have done Clean. Any more ideas?

**Comment by robbieboydcolenso** [comment]
Sorry, it's the error:

"OBJC_CLASS$_GoogleConversionPing", referenced from:
objc-class-ref in GoogleAppTracking.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pnock** [comment]
Most likely the underlying google library is an old version, and now that Apple require arm64, the linking fails.  I haven't had chance to look recently, but info for the Google code was at https://developers.google.com/app-conversion-tracking.  My code in GoogleAppTracking.m was simply a wrapper around their API.

The plugin bundles the ios library at lib/ios/libGoogleConversionTracking.a, try swapping in an updated version of that.  Though, chances are the calling API might have changed too.

**Comment by mlegenhausen** [comment]
You can try out my pull request #4. Should be fixed.
