### ISSUE TITLE
ios error on build

### ISSUE THREAD

**Issue by bigsassy** [MyHealthTeams/google-app-conversion-tracker#6]
When building for iOS I'm getting the following error:
    
    error: no known class method for selector '''reportWithConversionId:label:value:isRepeatable:'''

Does anything immediately come to mind that I could be doing wrong here?  I installed the plugin via `cordova plugin add https://github.com/MyHealthTeams/google-app-conversion-tracker.git` with no errors, and `AdSupport.framework` is linked in Xcode.

I have no idea what I'm doing wrong.  Can someone point me in the right direction?

**Comment by pnock** [comment]
Yes - hit me too :-) 

I just pushed a change.  Looks like the method changed on ios to "reportWithConversionID" - the "ID" part is now all upper case, not "Id".

**Comment by bigsassy** [comment]
Yup, that got it.  Thanks.
